[package]
name = "chemrust-scf"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
chemrust-hamiltonian-core = { path = "../chemrust-hamiltonian/chemrust-hamiltonian-core" }
ndarray = "0.17.2"
num-complex = "0.4.6"
thiserror = "2.0.18"
bon = "3.9.1"
libm = "0.2"
cudarc = { version = "0.19.7", features = ["cuda-12090", "cublas", "cufft", "cusolver", "nvrtc"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
rand = "0.8"

[features]
scf_diag = []

[dev-dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[lib]
name = "chemrust_scf"
crate-type = ["lib"]
